#!/usr/bin/env bash
# =============================================================================
# Task 13.3 — 前端集成验证
# Requirements: 6.13, 7.12, 9.5, 10.5, 10.6, 11.5, 13.4, 13.6
# =============================================================================
set -euo pipefail

PASS=0
FAIL=0
RESULTS=()

report() {
    local status="$1" name="$2" detail="$3"
    if [[ "$status" == "PASS" ]]; then
        PASS=$((PASS + 1))
        RESULTS+=("✓ $name: $detail")
    else
        FAIL=$((FAIL + 1))
        RESULTS+=("✗ $name: $detail")
    fi
}

TEMPLATE_DIR="slimvue-template"

echo "=== Task 13.3: 前端集成验证 ==="
echo ""

# --- 13.3.1 npm install ---
echo "[1/5] Running npm install..."
if npm install --prefix "$TEMPLATE_DIR" 2>&1; then
    report PASS "npm install" "completed without errors"
else
    report FAIL "npm install" "dependency resolution failed"
fi
echo ""

# --- 13.3.2 vitest run ---
echo "[2/5] Running vitest run..."
VITEST_OUTPUT=$(cd "$TEMPLATE_DIR" && npx vitest run 2>&1) || true
if echo "$VITEST_OUTPUT" | grep -qE 'Tests\s+[0-9]+ passed'; then
    VITEST_SUMMARY=$(echo "$VITEST_OUTPUT" | grep -E 'Tests\s+' | tail -1)
    # Check for failures
    if echo "$VITEST_SUMMARY" | grep -qE 'failed'; then
        report FAIL "vitest run" "$VITEST_SUMMARY"
    else
        report PASS "vitest run" "$VITEST_SUMMARY"
    fi
else
    VITEST_SUMMARY=$(echo "$VITEST_OUTPUT" | grep -E '(Tests|FAIL|Error)' | tail -1)
    report FAIL "vitest run" "${VITEST_SUMMARY:-tests did not pass}"
fi
echo ""

# --- 13.3.3 vitest coverage ---
echo "[3/5] Running vitest run --coverage..."
COVERAGE_OUTPUT=$(cd "$TEMPLATE_DIR" && npx vitest run --coverage 2>&1) || true

# Check for coverage summary — look for "All files" line
COVERAGE_ALL=$(echo "$COVERAGE_OUTPUT" | grep -E '^\s*All files' | head -1 || true)
if [[ -n "$COVERAGE_ALL" ]]; then
    # Extract the first percentage (Stmts or Lines)
    COV_PCT=$(echo "$COVERAGE_ALL" | grep -oE '[0-9]+(\.[0-9]+)?' | head -1)
    if [[ -n "$COV_PCT" ]]; then
        above=$(echo "$COV_PCT >= 90" | bc -l 2>/dev/null || echo "0")
        if [[ "$above" == "1" ]]; then
            report PASS "coverage" "overall ${COV_PCT}% (> 90%)"
        else
            report FAIL "coverage" "overall ${COV_PCT}% (below 90%)"
        fi
    else
        report FAIL "coverage" "could not parse coverage percentage"
    fi
else
    # Try alternative format
    COV_LINE=$(echo "$COVERAGE_OUTPUT" | grep -iE '(statements|lines|all files).*[0-9]+%' | head -1 || true)
    if [[ -n "$COV_LINE" ]]; then
        COV_PCT=$(echo "$COV_LINE" | grep -oE '[0-9]+(\.[0-9]+)?%' | head -1 | tr -d '%')
        above=$(echo "$COV_PCT >= 90" | bc -l 2>/dev/null || echo "0")
        if [[ "$above" == "1" ]]; then
            report PASS "coverage" "${COV_PCT}% (> 90%)"
        else
            report FAIL "coverage" "${COV_PCT}% (below 90%)"
        fi
    else
        report FAIL "coverage" "could not find coverage summary in output"
    fi
fi
echo ""

# --- 13.3.4 npm run build ---
echo "[4/5] Running npm run build..."
# Clean dist first
rm -rf "$TEMPLATE_DIR/dist"
BUILD_OUTPUT=$(npm run build --prefix "$TEMPLATE_DIR" 2>&1) || true
BUILD_EXIT=$?
if [[ -d "$TEMPLATE_DIR/dist" ]] && [[ $BUILD_EXIT -eq 0 ]]; then
    # Vite produces JS/CSS bundles in dist/assets/ — one per entry in src/entries/
    # The .twig page files are generated by the PHP CLI tool, not by Vite build
    ENTRY_COUNT=$(find "$TEMPLATE_DIR/src/entries" -name "*.js" 2>/dev/null | wc -l | tr -d ' ')
    JS_COUNT=$(find "$TEMPLATE_DIR/dist/assets" -name "*.js" 2>/dev/null | wc -l | tr -d ' ')
    CSS_COUNT=$(find "$TEMPLATE_DIR/dist/assets" -name "*.css" 2>/dev/null | wc -l | tr -d ' ')
    TOTAL_FILES=$(find "$TEMPLATE_DIR/dist" -type f 2>/dev/null | wc -l | tr -d ' ')
    if [[ $JS_COUNT -gt 0 ]]; then
        report PASS "build" "dist/ created: $JS_COUNT JS, $CSS_COUNT CSS, $TOTAL_FILES total files (from $ENTRY_COUNT entries)"
    else
        report FAIL "build" "dist/ exists but no JS bundles found"
    fi
else
    report FAIL "build" "build failed (exit $BUILD_EXIT) or dist/ not created"
    echo "  ↳ Output: $(echo "$BUILD_OUTPUT" | tail -5)"
fi
echo ""

# --- 13.3.5 npm run lint ---
echo "[5/5] Running npm run lint..."
LINT_OUTPUT=$(npm run lint --prefix "$TEMPLATE_DIR" 2>&1) || true
LINT_EXIT=$?
# Check for errors in output
if echo "$LINT_OUTPUT" | grep -qiE '(error|✗|✖)'; then
    ERROR_COUNT=$(echo "$LINT_OUTPUT" | grep -ciE '(error)' || echo "?")
    report FAIL "lint" "$ERROR_COUNT error(s) found"
else
    report PASS "lint" "zero errors"
fi
echo ""

# --- Summary ---
echo "==========================================="
echo "Task 13.3 Summary: $((PASS + FAIL)) checks, $PASS passed, $FAIL failed"
echo "==========================================="
for r in "${RESULTS[@]}"; do
    echo "  $r"
done
echo ""

exit $FAIL
